[project]
name = "dc-whois"
version = "0.1.0"
description = "Whois lookup module for demon-cry"
authors = [
    {name = "mooncore-inc"}
]
license = "Apache2"
readme = "README.md"
requires-python = ">=3.12, <3.15"
dependencies = [
    "demon-cry-base (>=0.1.0,<0.2.0)",
    "asyncwhois (>=1.1.12,<2.0.0)"
]

[project.entry-points."demon_cry.modules"]
whois_lookup = "dc_whois:WhoisLookup"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

